crmpage/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index),
    path('rejected/', views.rejected, name='rejected-applications'),
    path('later_on/', views.later_on, name='later-applications'),
    path('mpesa/', views.mpesa, name='mpesa'),
    path('student-card', views.student, name="student-card"),
    path('responses', views.separation, name="responses"),
    path('applications', views.applications, name="applications"),
    path('add-teacher', views.add_teacher, name="add-teacher"),
    path('add-student', views.add_student_view, name="add-student"),
    path('course_view', views.course_view, name="course_view"),
    path('class-pdf', views.getPdfPage, name="class-pdf"),
    path('crmpage/apps_edit/<int:pk>/<str:model_type>/', views.apps_edit, name='apps_edit'),  # Corrected path
    path('crmpage/eldoret_edit/<int:pk>/<str:model_type>/', views.eldoret_edit, name='eldoret_edit'),  # Corrected path
    path('crmpage/sheet2_edit/<int:pk>/', views.apps_edit, {'model_type': 'sheet2application'}, name='sheet2_edit'),
    path('edit_results/<int:candidate_id>/', views.edit_results, name='edit_results'),
    path('login', views.loginPage, name="login"),
    path('register', views.registerPage, name="register"),
    path('logout', views.logoutUser, name="logout"),
    path('success', views.success, name='success'),
    path('updated-candidates', views.updated_candidate, name='updated-candidates'),
    path('add-application', views.add_applications, name='add-application'),
    path('eldoret-application', views.add_eldored_applicant, name='eldoret-application'),
    path('enrolled_eldoret', views.enrolled_eldoret, name='enrolled_eldoret'),
    path('status-edit/(?P<pk>\d+)', views.status_edit, name='status-edit/(?P<pk>\d+)'),
    path('add-candidate', views.add_candidate, name='add-candidate'),
    path('update_database/', views.update_database, name='update_database'),
    path('update_sheet2_database/', views.update_sheet2_database, name='update-database'),
    path('model', views.model, name='model'),
    path('candidates/', views.candidate_list, name='candidate_list'),
    path('candidates/<int:candidate_id>/', views.candidate_detail, name='candidate_detail'),
    path('generate_invoice/<int:candidate_id>/', views.generate_invoice, name='generate_invoice'),
    path('candidates/<int:candidate_id>/upload_contract/', views.upload_contract, name='upload_contract'),
    path('record-attendance/<int:candidate_id>/', views.record_attendance, name='record_attendance'),
    path('attendance-details/', views.attendance_details, name='attendance_details'),
    path('attendance-details/<int:candidate_id>/', views.attendance_details, name='attendance_details'),
    path('payment-history/', views.payment_history_view, name='payment_history'),
    path('unique-payment/<int:candidate_id>/', views.unique_payments, name='unique_payment'),
    path('class_attendance/', views.class_attendance_record, name='class_attendance_record'),
    path('fee_structure/', views.create_fee_structure, name='fee_structure'),
    path('create_discount/', views.create_discount, name='create_discount'),
    path('update_candidates/', views.update_candidates, name='update_candidates'),
    path('edit_candidate/<int:pk>/<str:model_type>/', views.edit_candidate, name='edit_candidate'),
    path('class_fee/new/<int:candidate_id>/', views.create_class_fee, name='class_fee_new'),
    path('month-range/update/<int:month_id>/', views.update_month_range, name='update_month_range'),
    # new paths
    path('update-fees/<int:candidate_id>/', views.update_school_fees, name='update_fees'),
    path('schoolfee/<int:pk>/add/', views.SchoolFeeCreate.as_view(), name='schoolfee_add'),
    path('schoolfee/<int:pk>/update/', views.SchoolFeeUpdate.as_view(), name='schoolfee_update'),
    path('schoolfee/<int:pk>/delete/', views.SchoolFeeDelete.as_view(), name='schoolfee_delete'),
    # new admissions
    path('generate_admissions/<int:candidate_id>/', views.generate_admission, name='generate_admissions'),
    # index attendance
    path('index/<int:year>/<int:month>/', views.index, name='index_with_month'),
    # new FeeStructure
    path('generate_fee_structure/<int:candidate_id>/', views.generate_course_fee, name='Generate_Fee_Structure'),


]

crmsystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import JavaScriptCatalog
from crmsystem import settings
from django.conf.urls.static import static

urlpatterns = [
  path('jsi18n', JavaScriptCatalog.as_view(), name='js-catlog'),
  path('admin/', admin.site.urls),
  path('', include('crmpage.urls')),
  path('crmpage/', include('crmpage.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crmpage/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Response, Candidate, Application, Teacher, Student, Attendance, Sheet2Application, Contract
from .models import ClassAttendance, Eldoret_Applicant, FeeStructure, Discount
from .models import ClassFee, MonthRange
from .models import SchoolFee


# attendance details
class MonthSelectorForm(forms.Form):
    month_year = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'month'}),
        label="Month and Year",
        input_formats=['%Y-%m']  # This format will only consider year and month
    )


class DateInput(forms.DateInput):
    input_type = 'date'


class TimeInput(forms.TimeInput):
    input_type = 'time'


class SchoolFeeForm(forms.ModelForm):
    class Meta:
        model = SchoolFee
        fields = ['candidate', 'starting_month', 'due_date', 'total_amount_to_pay', 'invoice_number']
        widgets = {
            'starting_month': DateInput(),
            'due_date': DateInput(),
        }
        labels = {
            'candidate': 'Student Name',
            'starting_month': 'Starting Year',
        }

    def __init__(self, *args, **kwargs):
        super(SchoolFeeForm, self).__init__(*args, **kwargs)
        self.fields['candidate'].widget.attrs.update({'readonly': 'readonly', 'style': 'pointer-events: none;'})

        # If the form is bound to an existing instance, set the candidate field to its value
        if self.instance and self.instance.pk:
            self.initial['candidate'] = self.instance.candidate

    def clean_candidate(self):
        # If the form is bound to an existing instance, retain the original candidate value
        if self.instance and self.instance.pk:
            return self.instance.candidate
        # Otherwise, use the submitted value
        return self.cleaned_data['candidate']


class ClassFeeForm(forms.ModelForm):
    class Meta:
        model = ClassFee
        fields = ['class_assignment', 'starting_date', 'total_amount_to_pay']
        widgets = {
            'starting_date': DateInput(),

        }


class MonthRangeForm(forms.ModelForm):
    class Meta:
        model = MonthRange
        fields = ['month_name', 'amount_to_pay']
        widgets = {
            'month_name': DateInput(),

        }


class LevelForm(forms.Form):
    level = forms.ChoiceField(choices=Candidate.GERMAN)


class ClassAttendanceForm(forms.ModelForm):
    class Meta:
        model = ClassAttendance
        fields = ['date', 'present', 'absent_reason']


class EditCandidate(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = '__all__'
        widgets = {
            'Date_of_Birth': DateInput(),
            'child_date_of_birth': DateInput(),
            'child_date_of_birth2': DateInput(),
            'Schedule_Interview_date': DateInput(),
            'Schedule_Interview_time': DateInput(),

        }

    def __init__(self, *args, **kwargs):
        super(EditCandidate, self).__init__(*args, **kwargs)
        readonly_fields = ['admission_number']

        for field_name in readonly_fields:
            self.fields[field_name].widget.attrs.update({'readonly': 'readonly'})


class DiscountForm(forms.ModelForm):
    class Meta:
        model = Discount
        fields = ['discount_amount', 'date']
        widgets = {
            'date': DateInput(),

        }


class FeeStructureForm(forms.ModelForm):
    class Meta:
        model = FeeStructure
        fields = ['fee_assignment', 'total_amount_to_pay', 'starting_date', 'due_date']
        widgets = {
            'starting_date': DateInput(),
            'due_date': DateInput(),

        }


class AttendanceForm(forms.ModelForm):
    class Meta:
        model = Attendance
        exclude = ['candidate']
        fields = '__all__'
        widgets = {
            'date_of_class': DateInput(),
            'start_time': TimeInput(),
            'end_time': TimeInput(),
        }


class ContractUploadForm(forms.ModelForm):
    class Meta:
        model = Contract
        fields = ['signed_contract']


class YourInvoiceForm(forms.Form):
    Date_of_Payment = forms.DateField(label='Date of Payment', widget=forms.DateInput(attrs={'type': 'date'}))
    AmountPaid = forms.DecimalField(label='Amount Paid', max_digits=10, decimal_places=2, required=False)
    # Add other fields as needed


class AdmissionForm(forms.Form):
    Date_of_Admission = forms.DateField(label='Date of Payment', widget=forms.DateInput(attrs={'type': 'date'}))
    German_Level = forms.CharField(label='German Level', required=True)

class CourseFeeForm(forms.Form):
    Starting_Date = forms.DateField(label='Stating Course Date', widget=forms.DateInput(attrs={'type': 'date'}))
    Ending_Date = forms.DateField(label='EndingCourse Date', widget=forms.DateInput(attrs={'type': 'date'}))
    Amount_to_Pay = forms.CharField(label='Amount to Pay', required=True)

class CandidateFilterForm(forms.Form):
    ADDRESS_CHOICES = [
        ('Other', 'Other'),
        ('Mombasa', 'Mombasa (001)'),
        ('Kwale', 'Kwale (002 )'),
        ('Kilifi', 'Kilifi (003)'),
        ('Tana River', 'Tana River (004)'),
        ('Lamu', 'Lamu (005)'),
        ('Taita–Taveta', 'Taita–Taveta (006)'),
        ('Garissa', 'Garissa (007)'),
        ('Wajir', 'Wajir (008)'),
        ('Mandera', 'Mandera (009)'),
        ('Marsabit', 'Marsabit (010)'),
        ('Isiolo', 'Isiolo (011)'),
        ('Meru', 'Meru (012)'),
        ('Tharaka-Nithi', 'Tharaka-Nithi (013)'),
        ('Embu', 'Embu (014)'),
        ('Kitui', 'Kitui (015)'),
        ('Makueni', 'Makueni (017)'),
        ('Nyandarua', 'Nyandarua (018)'),
        ('Nyeri', 'Nyeri (019)'),
        ('Kirinyaga', 'Kirinyaga (020)'),
        ('Muranga', 'Muranga (021)'),
        ('Kiambu', 'Kiambu (022)'),
        ('Turkana', 'Turkana (023)'),
        ('West Pokot', 'West Pokot (024)'),
        ('Samburu', 'Samburu (025)'),
        ('Trans-Nzoia', 'Trans-Nzoia (026)'),
        ('Uasin Gishu', 'Uasin Gishu (027)'),
        ('Elgeyo-Marakwet', 'Elgeyo-Marakwet (028)'),
        ('Nandi Kapsabet', 'Nandi Kapsabet (029)'),
        ('Baringo Kabarnet', 'Baringo Kabarnet (030)'),
        ('Laikipia', 'Laikipia (031)'),
        ('Nakuru', 'Nakuru (032)'),
        ('Narok', 'Narok (033)'),
        ('Kajiado', 'Kajiado (034)'),
        ('Kericho', 'Kericho (035)'),
        ('Bomet', 'Bomet (036)'),
        ('Kakamega', 'Kakamega (037)'),
        ('Vihiga', 'Vihiga (038)'),
        ('Bungoma', 'Bungoma (039)'),
        ('Busia', 'Busia (040)'),
        ('Siaya', 'Siaya (041)'),
        ('Kisumu', 'Kisumu (042)'),
        ('Homa Bay', 'Homa Bay (043)'),
        ('Migori', 'Migori (044)'),
        ('Kisii', 'Kisii (045)'),
        ('Nyamira', 'Nyamira (046)'),
        ('Nairobi', 'Nairobi (047)'),
        # Add other choices as needed
    ]

    course_class_no = forms.CharField(max_length=255, required=False)
    course_intake = forms.CharField(max_length=255, required=False)
    address = forms.ChoiceField(choices=ADDRESS_CHOICES, required=False)
    # Add other fields as needed


class CandidateForm(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = '__all__'


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class CandidateInfo(forms.ModelForm):
    # Validations
    First_Name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    Last_Name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Last name'}))
    Other_Address = forms.CharField(label='Address Information', required=False,
                                    widget=forms.TextInput(attrs={'placeholder': 'Apartment, studio, or floor'}))
    Street_Address = forms.CharField(label='Street', required=False,
                                     widget=forms.TextInput(
                                         attrs={'placeholder': 'Africa 118, Westlands, Nairobi'}))
    Zip_Address = forms.CharField(label='Zip', required=False,
                                  widget=forms.TextInput(attrs={'placeholder': '00100'}))
    phone_number = forms.CharField(label='Primary Phone Number',
                                   widget=forms.TextInput(attrs={'placeholder': 'Input as (+254) 7***'}))
    secondary_phone_number = forms.CharField(label='Secondary Phone Number', required=False,
                                             widget=forms.TextInput(attrs={'placeholder': 'Input as (+254) 7***'}))
    emergency_contact = forms.CharField(label='Emergency Contact Person', required=False,
                                        widget=forms.TextInput(attrs={'placeholder': 'Their name'}))
    emergency_phone_number = forms.CharField(label='Emergency Contact', required=False,
                                             widget=forms.TextInput(attrs={'placeholder': 'Input as (+254) 7***'}))
    email_address = forms.CharField(label='Email Address',
                                    widget=forms.TextInput(attrs={'placeholder': 'user@gmail/outlook.com'}))
    secondary_email_address = forms.CharField(label='Secondary Email Address', required=False,
                                              widget=forms.TextInput(attrs={'placeholder': 'user@gmail/outlook.com'}))
    Licence_No = forms.CharField(label='Licence Number', required=False)
    High_School_name = forms.CharField(label='High School Name', required=True, )
    High_School_grade = forms.CharField(label='High School Grade',
                                        widget=forms.TextInput(attrs={'placeholder': 'KCSE Grade only (A-)'}))
    High_School_Year = forms.CharField(label='Year Attained',
                                       widget=forms.TextInput(attrs={'placeholder': '2008'}))
    High_School_Year_start = forms.CharField(label='Year Started',

crmpage/templates/generate_admission.html
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>AG-System </title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'img/german_flag.png' %}" rel="icon">
    <link href="{% static 'img/german_flag.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static '/css/style.css' %}" rel="stylesheet">
    <!--search form-->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <style>
        .invoice-form {
            max-width: 600px;
            margin: auto;
        }

        .invoice-form h2 {
            text-align: center;
        }

        .invoice-form form {
            margin-top: 20px;
        }

        .invoice-form button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
        }
           /* Add this style in the head section or your CSS file */
    button {
        background-color: #4CAF50; /* Green background color */
        color: white; /* White text color */
        padding: 10px 20px; /* Padding around text */
        border: none; /* No border */
        border-radius: 5px; /* Rounded corners */
        cursor: pointer; /* Cursor style on hover */
    }

    /* Add a hover effect */
    button:hover {
        background-color: #45a049; /* Darker green on hover */
    }
    </style>
</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="d-flex align-items-center justify-content-between">
        <a href="/" class="logo d-flex align-items-center">
            <img src="{% static 'img/german_flag.png' %}" alt="">
            <span class="d-none d-lg-block">AG System</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

</header><!-- End Header -->

<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
        <!-- Back Button -->
        <li class="nav-item">
            <a class="nav-link" href="javascript:history.go(-1);">
                <i class="bi bi-arrow-left"></i>
                <span>Back</span>
            </a>
        </li><!-- End Dashboard Nav -->
    </ul>
</aside><!-- End Sidebar-->

<main id="main" class="main">
{% if user.is_authenticated %}

    <div class="col-12">
        <div class="container overflow-auto">
            <div class="card-body">
                <h5 class="card-title">Generate Admissions <span> </span> </h5>
                <div class="container col-md-10 edit_box">
                    <div class="justify-content-center">
                        <div class="form-group container invoice-form">

                            <!-- Form Starts here -->
                            <form method="post" class="form">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit">Generate Admission</button>
                            </form><!-- end form -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 {% else %}

            <div class="pagetitle">
       <h1>CRM System</h1>
        <nav>
            <ol class="breadcrumb"> login to access the system
            </ol>
        </nav>
    </div><!-- End Page Title -->
          <section class="section align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center ">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
    <img src="{% static 'img/german_logo_new.png' %}" alt="">
     <h6><span><br>To Sign in <a href="login">Click here </a></span></h6>
    <p>Contact the administrator in case <br> any resource is not available.</p>
                    </div>
          </div>
        </div>

      </section>
    {% endif %}

</main><!-- End #main -->


<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/apexcharts/apexcharts.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/chart.js' %}/chart.umd.js' %}"></script>
<script src="{% static 'vendor/echarts/echarts.min.js' %}"></script>
<script src="{% static 'vendor/quill/quill.min.js' %}"></script>
<script src="{% static 'vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'vendor/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static '/js/main.js' %}"></script>

<!--form control-->
<script>
    $(document).ready(function () {
        $('#id_AmountPaid').select2();
    });
</script>
</body>

</html>

{% endblock %}

crmpage/templates/generate_fee_structure.html
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Fee Structure </title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'img/german_flag.png' %}" rel="icon">
    <link href="{% static 'img/german_flag.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static '/css/style.css' %}" rel="stylesheet">
    <!--search form-->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <style>
        .invoice-form {
            max-width: 600px;
            margin: auto;
        }

        .invoice-form h2 {
            text-align: center;
        }

        .invoice-form form {
            margin-top: 20px;
        }

        .invoice-form button {
            background-color: #007bff;
            color: #fff;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
        }
           /* Add this style in the head section or your CSS file */
    button {
        background-color: #4CAF50; /* Green background color */
        color: white; /* White text color */
        padding: 10px 20px; /* Padding around text */
        border: none; /* No border */
        border-radius: 5px; /* Rounded corners */
        cursor: pointer; /* Cursor style on hover */
    }

    /* Add a hover effect */
    button:hover {
        background-color: #45a049; /* Darker green on hover */
    }
    </style>
</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="d-flex align-items-center justify-content-between">
        <a href="/" class="logo d-flex align-items-center">
            <img src="{% static 'img/german_flag.png' %}" alt="">
            <span class="d-none d-lg-block">AG System</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

</header><!-- End Header -->

<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">
        <!-- Back Button -->
        <li class="nav-item">
            <a class="nav-link" href="javascript:history.go(-1);">
                <i class="bi bi-arrow-left"></i>
                <span>Back</span>
            </a>
        </li><!-- End Dashboard Nav -->
    </ul>
</aside><!-- End Sidebar-->

<main id="main" class="main">
{% if user.is_authenticated %}

    <div class="col-12">
        <div class="container overflow-auto">
            <div class="card-body">
                <h5 class="card-title">Generate Fee Structure <span> </span> </h5>
                <div class="container col-md-10 edit_box">
                    <div class="justify-content-center">
                        <div class="form-group container invoice-form">

                            <!-- Form Starts here -->
                            <form method="post" class="form">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit">Generate </button>
                            </form><!-- end form -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 {% else %}

            <div class="pagetitle">
       <h1>CRM System</h1>
        <nav>
            <ol class="breadcrumb"> login to access the system
            </ol>
        </nav>
    </div><!-- End Page Title -->
          <section class="section align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center ">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
    <img src="{% static 'img/german_logo_new.png' %}" alt="">
     <h6><span><br>To Sign in <a href="login">Click here </a></span></h6>
    <p>Contact the administrator in case <br> any resource is not available.</p>
                    </div>
          </div>
        </div>

      </section>
    {% endif %}

</main><!-- End #main -->


<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'vendor/apexcharts/apexcharts.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/chart.js' %}/chart.umd.js' %}"></script>
<script src="{% static 'vendor/echarts/echarts.min.js' %}"></script>
<script src="{% static 'vendor/quill/quill.min.js' %}"></script>
<script src="{% static 'vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'vendor/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static '/js/main.js' %}"></script>

<!--form control-->
<script>
    $(document).ready(function () {
        $('#id_AmountPaid').select2();
    });
</script>
</body>

</html>

{% endblock %}

crmpage/templates/pdf_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Class List</title>
    <style>
        th, td {
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: black;
            color: white;
        }

        @page {
            size: a4 landscape;
            margin: 20mm;  /* Adjust the margin as needed */
        }

        .signature-column {
            width: 100px;
            height: 50px;
        }
    </style>
</head>
<body>

{% for teacher in teacher %}
    <h5 class="card-title">{{ teacher.course_class_no }} - {{ teacher.course_intake }}</h5>
    <h6>Teacher Name: {{ teacher.lec_first_name }} {{ teacher.lec_last_name }}</h6>
    <h3>Participants</h3>

    <table id="example" class="table table-striped overflow-auto" border="1" style="width:100%">
        <thead>
        <tr>
            <th class="signature-column">Student</th>
            {% for day in weekdays_range %}
                <th class="signature-column">{{ day|date:"D d M" }}</th>
                <!-- Add more signature columns as needed -->
            {% endfor %}
        </tr>
        </thead>

        <tbody>
        {% for candidates in candidates %}
            {% if candidates.course_intake == teacher.course_intake %}
                <tr>
                    <td>{{ candidates.First_Name }} {{ candidates.Last_Name }}</td>
                    {% for _ in weekdays_range %}
                        <td class="signature-column"></td>
                        <!-- Add more signature columns as needed -->
                    {% endfor %}
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

{% endfor %}
</body>
</html>